on:
  push:
    branches:
      - main

jobs:
  use_ssh_agent:
    runs-on: ubuntu-latest
    name: Publish Sub-split
    steps:
      - name: Cache multiple paths
        uses: actions/cache@v2
        with:
          path: ./temp/splitsh-lite
          key: ${{ runner.os }}-splitsh-lite

      - uses: actions/checkout@v1
      - uses: ./
