# This is changed
on:
  push:
    branches:
      - main

jobs:
  use_ssh_agent:
    runs-on: ubuntu-latest
    name: Publish Sub-split
    steps:
      - uses: frankdejonge/use-github-token@1.0.1
        with:
          authentication: 'frankdejonge:${{ secrets.PERSONAL_GITHUB_TOKEN }}'
          user_name: 'Frank de Jonge'
          user_email: 'info@frenky.net'
      - name: Cache splitsh-lite
        uses: actions/cache@v2
        with:
          path: '~/splitsh-lite'
          key: '${{ runner.os }}-splitsh-lite'

      - uses: actions/checkout@v1

      - uses: ./
        with:
          source-branch: 'main'
          config-path: './config.subsplit-publish.json'
          splitsh-path: '~/splitsh-lite'
          splitsh-version: 'v1.0.1'
